### ISSUE TITLE
Cannot use with Android Studio 1.2 preview 3

### ISSUE THREAD

**Issue by yshrsmz** [bunnyblue/SerializableParcelableGenerator#2]
Hi, Installed this plugin on Android Studio 1.2 preview 3, and got this error.

```java
Null child action in group Generate () of class class com.intellij.openapi.actionSystem.DefaultActionGroup, id=generateParcelableNew
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:115)
	at com.intellij.openapi.actionSystem.DefaultActionGroup.unStub(DefaultActionGroup.java:356)
	at com.intellij.openapi.actionSystem.DefaultActionGroup.getChildren(DefaultActionGroup.java:312)
	at com.intellij.openapi.actionSystem.ActionGroupUtil.isGroupEmpty(ActionGroupUtil.java:45)
	at com.intellij.openapi.actionSystem.ActionGroupUtil.isGroupEmpty(ActionGroupUtil.java:39)
	at com.intellij.codeInsight.generation.actions.GenerateAction.update(GenerateAction.java:65)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:114)
	at com.intellij.ide.util.gotoByName.GotoActionModel.updateActionBeforeShow(GotoActionModel.java:273)
	at com.intellij.ide.util.gotoByName.GotoActionModel$ActionWrapper.getPresentation(GotoActionModel.java:593)
	at com.intellij.ide.util.gotoByName.GotoActionModel$ActionWrapper.isAvailable(GotoActionModel.java:588)
	at com.intellij.ide.util.gotoByName.GotoActionModel$ActionWrapper.access$000(GotoActionModel.java:550)
	at com.intellij.ide.util.gotoByName.GotoActionModel$MatchedValue.compareTo(GotoActionModel.java:181)
	at com.intellij.ide.util.gotoByName.GotoActionModel.compare(GotoActionModel.java:268)
	at java.util.TreeMap.put(TreeMap.java:530)
	at java.util.TreeSet.add(TreeSet.java:238)
	at java.util.AbstractCollection.addAll(AbstractCollection.java:305)
	at java.util.TreeSet.addAll(TreeSet.java:295)
	at com.intellij.ide.util.gotoByName.GotoActionModel.sort(GotoActionModel.java:434)
	at com.intellij.ide.actions.GotoActionAction$2.filter(GotoActionAction.java:116)
	at com.intellij.ide.util.gotoByName.ChooseByNameBase$CalcElementsThread$1.run(ChooseByNameBase.java:1532)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:332)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
	at java.awt.EventQueue.access$400(EventQueue.java:82)
	at java.awt.EventQueue$2.run(EventQueue.java:676)
	at java.awt.EventQueue$2.run(EventQueue.java:674)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
```

**Comment by bunnyblue** [comment]
you can try  at https://github.com/bunnyblue/SerializableParcelableGenerator/releases/tag/1.2   https://plugins.jetbrains.com/plugin/7714 staus is Wait for approve
it should work

**Comment by bunnyblue** [comment]
If not usable,reopen this issue,thanks for your report
